apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: mongodb-restapi
spec:
  targetNamespaces:
  - restapi-mongodb
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-percona-server-mongodb-operator
  namespace: mongodb-restapi
spec:
  channel: stable
  name: percona-server-mongodb-operator-certified-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace

