apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  creationTimestamp: null
  name: restapi-perconaservermongodb-mongo-cluster2
spec:
  application:
    group: apps
    name: restapi-app
    resource: deployments
    version: v1
  bindAsFiles: true
  detectBindingResources: true
  services:
  - group: psmdb.percona.com
    id: mongo-cluster2
    kind: PerconaServerMongoDB
    name: mongo-cluster2
    version: v1-11-0
status:
  secret: ""
