apiVersion: psmdb.percona.com/v1-11-0
kind: PerconaServerMongoDB
metadata:
  name: mongo-cluster2
spec:
  allowUnsafeConfigurations: true
  crVersion: 1.11.0
  image: percona/percona-server-mongodb:4.4.10-11
  platform: openshift
  replsets:
  - name: rs0
    size: 1
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
  secrets:
    users: mongo-cluster-secrets
  sharding:
    configsvrReplSet:
      size: 1
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 1Gi
    enabled: true
    mongos:
      size: 1
  upgradeOptions:
    apply: 4.4-recommended
    schedule: 0 2 * * *
